name: CI
on: [pull_request, push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: psf/black@24.4.2

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./dev-requirements.txt
      - name: Build Wheel
        run: |
          python setup.py sdist
          python setup.py bdist_wheel
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  test:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', 'pypy3.9']
        sphinx-version: ['5.*', '6.*', '7.*']

    name: "Test - Python(${{ matrix.python-version }}), Sphinx(${{ matrix.sphinx-version }})"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dev Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./dev-requirements.txt
          python -m pip install sphinx==${{ matrix.sphinx-version }}

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Install package
        run: |
          pip install dist/*.whl

      - name: Run Tests for ${{ matrix.python-version }}
        run: |
          cd tests
          python -m pytest -vv

  pypi-release:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: contains(github.ref, 'refs/tags/') && github.repository_owner	== 'wpilibsuite'
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
